# Generated by Django 4.2.9 on 2024-01-25 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_team'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='tdesc',
            new_name='desc',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='timg',
            new_name='img',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='tname',
            new_name='name',
        ),
    ]
